/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.76.12
  Forc version: 0.51.1
  Fuel-Core version: 0.22.1
*/

export type { ContractCounterAbi } from './ContractCounterAbi';

export { ContractCounterAbi__factory } from './factories/ContractCounterAbi__factory';
